<?php
error_reporting(E_ERROR | E_PARSE);
ini_set('display_errors', '0');
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { http_response_code(405); echo json_encode(['ok'=>false,'error'=>'POST required']); exit; }

$raw = file_get_contents('php://input');
$data = json_decode($raw, true);
if (!$data) { http_response_code(400); echo json_encode(['ok'=>false,'error'=>'Invalid JSON']); exit; }

$root = dirname(__DIR__);
$dir = $root . '/data';
$backupDir = $dir . '/backups';

if (!is_dir($dir)) mkdir($dir, 0755, true);
if (!is_dir($backupDir)) mkdir($backupDir, 0755, true);

$jsonPath = $dir . '/receta.json';
$jsPath   = $root . '/js/saved-config.js';

// backup
if (file_exists($jsonPath)) {
    $ts = date('Y-m-d_H-i-s');
    copy($jsonPath, "$backupDir/receta.backup-$ts.json");
    // keep only last 20 backups
    $backups = glob("$backupDir/receta.backup-*.json");
    sort($backups);
    if (count($backups) > 20) {
        foreach (array_slice($backups, 0, count($backups) - 20) as $old) unlink($old);
    }
}

// write JSON
$json = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
file_put_contents($jsonPath, $json, LOCK_EX);

// burn JS
$js = "// Auto-generated by save.php — do not edit manually\nwindow.SAVED_DATA = " . $json . ";\n";
file_put_contents($jsPath, $js, LOCK_EX);

echo json_encode(['ok'=>true, 'ts'=>date('c')]);
